//
//  QPoll.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.4
//

import Foundation
import UIKit
import AWSDynamoDB

class QPoll: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _answer1Percentage: NSNumber?
    var _answer1String: String?
    var _answer2Percentage: NSNumber?
    var _answer2String: String?
    var _expirationTime: NSNumber?
    var _expired: NSNumber?
    var _pollID: String?
    var _questionString: String?
    var _recipientUsers: String?
    
    class func dynamoDBTableName() -> String {

        return "qmessenger-mobilehub-702537144-q_poll"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
   
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable : Any] {
        return [
               "_userId" as AnyHashable : "userId" as AnyObject,
               "_answer1Percentage" as AnyHashable : "answer1Percentage" as Any,
               "_answer1String" as AnyHashable : "answer1String" as Any,
               "_answer2Percentage" as AnyHashable : "answer2Percentage" as Any,
               "_answer2String" as AnyHashable : "answer2String" as Any,
               "_expirationTime" as AnyHashable : "expirationTime" as Any,
               "_expired" as AnyHashable : "expired" as Any,
               "_pollID" as AnyHashable : "pollID" as Any,
               "_questionString" as AnyHashable : "questionString" as Any,
               "_recipientUsers" as AnyHashable : "recipientUsers" as Any,
        ]
    }
}
