//
//  QUser.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.4
//

import Foundation
import UIKit
import AWSDynamoDB
import AWSMobileHubHelper

class QUser: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _pollsReceived: Set<String>?
    var _pollsSent: Set<String>?
    var _profileImageURL: String?
    var _userName: String?
    var _userPhoneNumber: String?
    
    
    class func dynamoDBTableName() -> String {

        return "qmessenger-mobilehub-702537144-q_user"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
   
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable : Any] {
        return [
               "_userId" as AnyHashable : "userId" as Any,
               "_pollsReceived" as AnyHashable : "pollsReceived" as Any,
               "_pollsSent" as AnyHashable : "pollsSent" as Any,
               "_profileImageURL" as AnyHashable : "profileImageURL" as Any,
               "_userName" as AnyHashable : "userName" as Any,
               "_userPhoneNumber" as AnyHashable : "userPhoneNumber" as Any,
        ]
    }
}
